using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CiltKocum.Web.Models
{
    // Main response package coming from our Python AI microservice
    public class AiResponseDto
    {
        // The text advice generated by the LLM
        [JsonPropertyName("response_text")]
        public string ResponseText { get; set; }

        // The specific active ingredient found by AI (e.g., Salicylic Acid)
        [JsonPropertyName("active_ingredient")]
        public string ActiveIngredient { get; set; }

        // List of scraped products to show on the UI
        [JsonPropertyName("live_products")]
        public List<LiveProductDto> LiveProducts { get; set; }
    }

    // Represents a single scraped product inside the live_products list
    public class LiveProductDto
    {
        // Name of the scraped product
        [JsonPropertyName("name")]
        public string Name { get; set; }

        // Price of the product as a string
        [JsonPropertyName("price")]
        public string Price { get; set; }

        // URL of the product image to render in HTML
        [JsonPropertyName("image_url")]
        public string ImageUrl { get; set; }

        // The external link to buy the product
        [JsonPropertyName("purchase_link")]
        public string PurchaseLink { get; set; }
    }
}